#pragma once

//#include <GLFW/glfw3.h>

namespace Key {
    constexpr int SPACE = 32;
    constexpr int APOSTROPHE = 39;  /* ' */
    constexpr int COMMA = 44;  /* ; */
    constexpr int MINUS = 45;  /* - */
    constexpr int PERIOD = 46;  /* . */
    constexpr int SLASH = 47;  /* / */
    constexpr int ZERO = 48;
    constexpr int ONE = 49;
    constexpr int TWO = 50;
    constexpr int THREE = 51;
    constexpr int FOUR = 52;
    constexpr int FIVE = 53;
    constexpr int SIX = 54;
    constexpr int SEVEN = 55;
    constexpr int EIGHT = 56;
    constexpr int NINE = 57;
    constexpr int SEMICCOLON = 59;  /* ; */
    constexpr int EQUAL = 61;  /* = */
    constexpr int A = 65;
    constexpr int B = 66;
    constexpr int C = 67;
    constexpr int D = 68;
    constexpr int E = 69;
    constexpr int F = 70;
    constexpr int G = 71;
    constexpr int H = 72;
    constexpr int I = 73;
    constexpr int J = 74;
    constexpr int K = 75;
    constexpr int L = 76;
    constexpr int M = 77;
    constexpr int N = 78;
    constexpr int O = 79;
    constexpr int P = 80;
    constexpr int Q = 81;
    constexpr int R = 82;
    constexpr int S = 83;
    constexpr int T = 84;
    constexpr int U = 85;
    constexpr int V = 86;
    constexpr int W = 87;
    constexpr int X = 88;
    constexpr int Y = 89;
    constexpr int Z = 90;
    constexpr int ESCAPE = 256;
    constexpr int ENTER = 257;
    constexpr int TAB = 258;
    constexpr int BACKSPACE = 259;
    constexpr int INSERT = 260;
    constexpr int DEL = 261;
    constexpr int RIGHT = 262;
    constexpr int LEFT = 263;
    constexpr int DOWN = 264;
    constexpr int UP = 265;
    constexpr int PAGE_UP = 266;
    constexpr int PAGE_DOWN = 267;
    constexpr int HOME = 268;
    constexpr int END = 269;
    constexpr int CAPS_LOCK = 280;
    constexpr int SCROLL_LOCK = 281;
    constexpr int NUM_LOCK = 282;
    constexpr int PRINT_SCREEN = 283;
    constexpr int PAUSE = 284;
    constexpr int F1 = 290;
    constexpr int F2 = 291;
    constexpr int F3 = 292;
    constexpr int F4 = 293;
    constexpr int F5 = 294;
    constexpr int F6 = 295;
    constexpr int F7 = 296;
    constexpr int F8 = 297;
    constexpr int F9 = 298;
    constexpr int F10 = 299;
    constexpr int F11 = 300;
    constexpr int F12 = 301;
    constexpr int F13 = 302;
    constexpr int F14 = 303;
    constexpr int F15 = 304;
    constexpr int F16 = 305;
    constexpr int F17 = 306;
    constexpr int F18 = 307;
    constexpr int F19 = 308;
    constexpr int F20 = 309;
    constexpr int F21 = 310;
    constexpr int F22 = 311;
    constexpr int F23 = 312;
    constexpr int F24 = 313;
    constexpr int F25 = 314;
    constexpr int KP_0 = 320;
    constexpr int KP_1 = 321;
    constexpr int KP_2 = 322;
    constexpr int KP_3 = 323;
    constexpr int KP_4 = 324;
    constexpr int KP_5 = 325;
    constexpr int KP_6 = 326;
    constexpr int KP_7 = 327;
    constexpr int KP_8 = 328;
    constexpr int KP_9 = 329;
    constexpr int KP_DECIMAL = 330;
    constexpr int KP_DIVIDE = 331;
    constexpr int KP_MULTIPLY = 332;
    constexpr int KP_SUBTRACT = 333;
    constexpr int KP_ADD = 334;
    constexpr int KP_ENTER = 335;
    constexpr int KP_EQUAL = 336;
    constexpr int LEFT_SHIFT = 340;
    constexpr int LEFT_CONTROL = 341;
    constexpr int LEFT_ALT = 342;
    constexpr int LEFT_SUPER = 343;
    constexpr int RIGHT_SHIFT = 344;
    constexpr int RIGHT_CONTROL = 345;
    constexpr int RIGHT_ALT = 346;
    constexpr int RIGHT_SUPER = 347;
    constexpr int MENU = 348;
}

namespace Mouse {
    constexpr int LEFT = 0;
    constexpr int RIGHT = 1;
    constexpr int MIDDLE = 2;
}